In [1]:
#importing required liberary
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#import datasets
data=pd.read_csv("data.txt",names=['x1','x2','y']);

In [3]:
#reading 5 dataset
data.head()

x1         x2  y
0  34.623660  78.024693  0
1  30.286711  43.894998  0
2  35.847409  72.902198  0
3  60.182599  86.308552  1
4  79.032736  75.344376  1

In [4]:
data.loc[:, 'y'].replace([0,1], [-1.0,1.0], inplace=True)

In [5]:
data.head()

x1         x2    y
0  34.623660  78.024693 -1.0
1  30.286711  43.894998 -1.0
2  35.847409  72.902198 -1.0
3  60.182599  86.308552  1.0
4  79.032736  75.344376  1.0

In [6]:
#no of -1.0 in y
np.sum(data['y']==-1.0)

40

In [7]:
#no of 1 in y
np.sum(data['y']==1.0)

60

In [8]:
#viewing size of dataset
data['x1'].size

100

In [9]:
#normalizing
data['x1']=((data['x1']-data['x1'].min())/(data['x1'].max()-data['x1'].min()))
data['x2']=((data['x2']-data['x2'].min())/(data['x2'].max()-data['x2'].min()))

In [10]:
data.head()

x1        x2    y
0  0.065428  0.694655 -1.0
1  0.003266  0.194705 -1.0
2  0.082968  0.619618 -1.0
3  0.431764  0.816001  1.0
4  0.701943  0.655392  1.0

In [11]:
i=28
j=42
k=0
tr=0
te=0
x1=np.zeros(70)
x2=np.zeros(70)
y=np.zeros(70)
x1_test=np.zeros(30)
x2_test=np.zeros(30)
y_test=np.zeros(30)
for k in range(100):
    if data.loc[k,'y']==-1.0 and i>0:
        x1[tr]=data.loc[k,'x1']
        x2[tr]=data.loc[k,'x2']
        y[tr]=data.loc[k,'y']
        i=i-1
        tr=tr+1
    elif data.loc[k,'y']==1.0 and j>0:
        x1[tr]=data.loc[k,'x1']
        x2[tr]=data.loc[k,'x2']
        y[tr]=data.loc[k,'y']
        j=j-1
        tr=tr+1
    else:
        x1_test[te]=data.loc[k,'x1']
        x2_test[te]=data.loc[k,'x2']
        y_test[te]=data.loc[k,'y']
        te=te+1

In [12]:
#Taking 70% of data as training set
#k=(int)(0.7*data['x1'].size)
#x1=np.array(data.loc[:k-1,'x1'])
#x2=np.array(data.loc[:k-1,'x2'])
#y=np.array(data.loc[:k-1,'y'])

In [13]:
#checking Size of training set
len(x1)

70

In [14]:
#Taking rest 30% as test data
#x1_test=np.array(data.loc[k:,'x1'])
#x2_test=np.array(data.loc[k:,'x2'])
#y_test=np.array(data.loc[k:,'y'])

In [15]:
#linear regression model
x1x1=x1*x1
x1x1_mean=x1x1.mean()

In [16]:
x1x2=x1*x2
x1x2_mean=x1x2.mean()

In [17]:
x1_mean=x1.mean()

In [18]:
x1y=x1*y
x1y_mean=x1y.mean()

In [19]:
x2x2=x2*x2
x2x2_mean=x2x2.mean()

In [20]:
x2_mean=x2.mean()

In [21]:
x2y=x2*y
x2y_mean=x2y.mean()

In [22]:
y_mean=y.mean()

In [23]:
#creating augmented matrix
M=np.array([[x1x1_mean, x1x2_mean, x1_mean,  x1y_mean],
            [x1x2_mean, x2x2_mean, x2_mean,  x2y_mean],
            [x1_mean,   x2_mean,   1.0,      y_mean]])
print(M)

[[0.33511774 0.26085885 0.50929728 0.25030647]
 [0.26085885 0.35578309 0.53285541 0.22778756]
 [0.50929728 0.53285541 1.         0.2       ]]


In [24]:
#performing row operation R2->R2-(M20/M00)R0
M[2,:]=M[2,:]-(M[2,0]/M[0,0])*M[0,:]
print(M)

[[ 0.33511774  0.26085885  0.50929728  0.25030647]
 [ 0.26085885  0.35578309  0.53285541  0.22778756]
 [ 0.          0.13641355  0.22599227 -0.18040482]]


In [25]:
#performing row operation R1->R1-(M10/M00)R0
M[1,:]=M[1,:]-(M[1,0]/M[0,0])*M[0,:]
print(M)

[[ 0.33511774  0.26085885  0.50929728  0.25030647]
 [ 0.          0.15272807  0.13641355  0.03294662]
 [ 0.          0.13641355  0.22599227 -0.18040482]]


In [26]:
#performing row operation R2->R2-(M21/M11)R1
M[2,:]=M[2,:]-(M[2,1]/M[1,1])*M[1,:]
print(M)

[[ 0.33511774  0.26085885  0.50929728  0.25030647]
 [ 0.          0.15272807  0.13641355  0.03294662]
 [ 0.          0.          0.10415052 -0.20983205]]


In [27]:
#Calculating constant k=M23/M22
k=M[2,3]/M[2,2]
print(k)

-2.014699931445252


In [28]:
#calculating cofficient w2=(M13-k*M12)/M11
w2=(M[1,3]-k*M[1,2])/M[1,1]
print(w2)

2.0152089821283607


In [29]:
#calculating cofficient w1=(M03-(w2*M01+k*M02))/M00
w1=(M[0,3]-(w2*M[0,1]+k*M[0,2])/M[0,0])
print(w1)

1.7435013823586132


In [30]:
m=0.0
m=len(x1)#size of train data
alpha=0.1#learning rate

In [31]:
for j in range(300000):
    Ew1=0.0
    Ew2=0.0
    Ek=0.0
    for i in range(m):
        s=w1*x1[i]+w2*x2[i]+k
        Ew1=Ew1+((y[i]*x1[i])/(1+np.exp(y[i]*s)))
        Ew2=Ew2+((y[i]*x2[i])/(1+np.exp(y[i]*s)))
        Ek=Ek+(y[i]/(1+np.exp(y[i]*s)))
    Ew1=(-1*Ew1)/m
    Ew2=(-1*Ew2)/m
    Ek=(-1*Ek)/m
    w1=w1-alpha*Ew1
    w2=w2-alpha*Ew2
    k=k-alpha*Ek

In [32]:
y_test[y_test==-1.0]=0.0
c=0
for i in range(len(x1_test)):
    s=w1*x1_test[i]+w2*x2_test[i]+k
    p=1/(1+np.exp(-1*s))
    if p.round()==y_test[i]:
        c+=1
print(c/len(x1_test))

0.9


In [33]:
y[y==-1.0]=0.0
c=0
for i in range(len(x1)):
    s=w1*x1[i]+w2*x2[i]+k
    p=1/(1+np.exp(-1*s))
    if p.round()==y[i]:
        c+=1
print(c/len(x1))

0.9
